djordan/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from django.conf import settings
from djordan import views


urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('room/', include('room.urls')),
    path('profile/', include('user_profile.urls')),
    # path('accounts/login/', TemplateView.as_view(template_name="registration/login.html"), name='login'),
    # path('accounts/logout/', auth_views.logout_then_login, name='logout'),
    # path('accounts/login/', auth_views.LoginView.as_view(template_name='user_profile/login.html')),
    path('accounts/', include('django.contrib.auth.urls')), # django built-in auth library REGISTRATION FOLDER
    # path('events2/', include('events2.urls')),
]

room/urls.py
from django.urls import path

from room import views
from room.views import GeneratePDF


urlpatterns = [
    path('guests/', views.guest_list, name='hotel_guest_list'),
    path('occupied/', views.occupied_guest_list, name='occupied_guest_list'),
    path('checkedout/', views.checkedout_guest_list, name='checkedout_guest_list'),
    path('newguests/', views.new_guest, name='hotel_new_guest'),
    path('rooms/', views.room_list, name='hotel_room_list'),
    path('checkout/<int:id>/', views.pre_check_out, name='pre_check_out'),
    path('checkout/<int:id>/pay/', views.pay_check_out, name='pay_check_out'),
    path('checkout/<int:id>/paid/', views.paid_check_out, name='paid_check_out'),
    path('change/<int:id>/', views.change_departure_date, name='change_date'),
    path('facilities/', views.facility_list, name='hotel_facility_list'),
    path('booking/<int:id>/', views.booking, name='hotel_booking'),
    path('facility/booking/', views.booking_facility, name='booking_facility'),
    path('booked/facility', views.booked_facilities, name='booked_facilities'),
    # <int:day>/<int:month>/<int:year>/
    path('housekeeping/',
         views.housekeeping, name='hotel_housekeeping_list'),
    path('requisition/<int:id>/',
         views.requisition, name='hotel_requisition'),
    path('requisition/', views.new_requisition, name='hotel_requisition_new'),
    path('bill/<int:id>/', views.bills, name='hotel_bill_list'),
    path('inventory/<int:id>/', views.inventory, name='hotel_inventory_list'),
    path('purchase/<int:id>/', views.purchase, name='hotel_purchase'),
    path('purchase/', views.new_purchase, name='hotel_purchase_new'),
    path('transfer/', views.transfer, name='hotel_transfer'),
    path('print/<int:id>/', GeneratePDF.as_view(), name='print_bill_pdf'),
    path('occupied/dates/', views.view_room_with_date, name='view_room_with_date'),
]

room/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone


class RoomType(models.Model):
    name = models.CharField(max_length=100)
    cost = models.DecimalField(decimal_places=2, max_digits=10)
    deposit = models.DecimalField(decimal_places=2, max_digits=10)

    def __str__(self):
        return self.name


class Room(models.Model):
    room_number = models.CharField(max_length=100)
    room_type = models.ForeignKey(RoomType, on_delete=models.CASCADE)
    occupied = models.BooleanField(default=False)

    def __str__(self):
        return '{} - {} ({})'.format(
            self.room_number, self.room_type, self.room_type.cost)


class CompanyAccount(models.Model):
    name = models.CharField(max_length=100)
    address = models.TextField()
    balance = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.name


class Guest(models.Model):
    SELECT = 0
    FEMALE = 1
    MALE = 2
    SEXES = enumerate(('Select', 'Female', 'Male'))

    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    deposit = models.DecimalField(decimal_places=2, max_digits=10)
    surname = models.CharField(max_length=200)
    other_names = models.CharField(max_length=200)
    sex = models.PositiveIntegerField(choices=SEXES, default=0)
    nationality = models.CharField(max_length=100)
    occupation = models.CharField(max_length=100)
    address = models.TextField(blank=True)
    car_number = models.CharField(max_length=20)
    phone_number = models.CharField(max_length=20)
    email = models.EmailField()
    purpose = models.CharField(max_length=20, blank=True)
    arriving_from = models.CharField(max_length=20, blank=True)
    travelling_to = models.CharField(max_length=20, blank=True)
    passport_no = models.CharField(max_length=20, blank=True)
    arrival_date = models.DateField(default=timezone.now)
    departure_date = models.DateField(null=True, blank=True)
    account = models.ForeignKey(CompanyAccount, null=True, blank=True, on_delete=models.SET_NULL)
    num_adults = models.IntegerField()
    num_children = models.IntegerField()
    checked_out = models.BooleanField(default=False)

    def __str__(self):
        return self.surname

    @property
    def full_name(self):
        return '{} {}'.format(self.other_names, self.surname)

    class Meta:
        ordering = ["-id", "-arrival_date"]


class Facility(models.Model):
    name = models.CharField(max_length=200)
    cost = models.DecimalField(max_digits=10, decimal_places=2)
    occupied = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Booking(models.Model):
    facility = models.ForeignKey(Facility, on_delete=models.CASCADE)
    booked_date = models.DateField()
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    name = models.CharField(max_length=200, blank=True)
    phone = models.CharField(max_length=50, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return unicode(self.facility)


class HouseKeeping(models.Model):
    name = models.CharField(max_length=100)
    rate = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.IntegerField()
    reorder_level = models.IntegerField(default=1)

    def __str__(self):
        return self.name


class RequisitionMaster(models.Model):
    date = models.DateField(default=timezone.now)

    def __str__(self):
        return self.date.strftime('%Y-%m-%d')


class Requisition(models.Model):
    item = models.ForeignKey(HouseKeeping, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    rate = models.DecimalField(max_digits=10, decimal_places=2)
    master = models.ForeignKey(RequisitionMaster, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return unicode(self.item)


class Bill(models.Model):
    RESTAURANT = 0
    MAIN_BAR = 1
    SWIMMING_POOL_BAR = 2
    LAUNDRY = 3
    GYM = 4
    SERVICES = enumerate(
        ('Restaurant', 'Main Bar', 'Pool Bar', 'Laundry', 'Gym'))

    guest = models.ForeignKey(Guest, null=True, on_delete=models.SET_NULL)
    amount = models.DecimalField(decimal_places=2, max_digits=10)
    bill_date = models.DateField(default=timezone.now)
    paid = models.BooleanField(default=False)
    description = models.TextField(blank=True)
    service = models.PositiveIntegerField(choices=SERVICES)

    def __str__(self):
        return '{}'.format(self.amount)

    @property
    def pending(self):
        return not self.paid


class Item(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.name


class Inventory(models.Model):
    RESTAURANT = 0
    MAIN_BAR = 1
    SWIMMING_POOL_BAR = 2
    STORE = 3
    SELECT = 4
    LOCATIONS = enumerate(
        ('Restaurant', 'Main Bar', 'Pool Bar', 'Store', 'Select Location'))

    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    location = models.PositiveIntegerField(choices=LOCATIONS, default=4)

    def __str__(self):
        return unicode(self.item)


class PurchaseMaster(models.Model):
    when = models.DateField(default=timezone.now)

    def __str__(self):
        return self.when.strftime('%d-%m-%Y')


class Purchase(models.Model):
    master = models.ForeignKey(PurchaseMaster, null=True, on_delete=models.SET_NULL)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return unicode(self.inventory)

    @property
    def total(self):
        return self.quantity * self.price


class Transfer(models.Model):
    RESTAURANT = 0
    MAIN_BAR = 1
    SWIMMING_POOL_BAR = 2
    LOCATIONS = enumerate(
        ('Restaurant', 'Main Bar', 'Pool Bar'))

    destination = models.PositiveIntegerField(choices=LOCATIONS)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    when = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return '{} - {}'.format(self.destination, self.item)

room/forms.py
from django import forms

from room.models import Guest, Room, Booking, Requisition, Purchase,\
    Transfer, Facility, HouseKeeping, Bill, Inventory, Item


class GuestForm(forms.ModelForm):
    queryset = Room.objects.filter(occupied=False)
    room = forms.ModelChoiceField(queryset, empty_label="Select type")
    departure_date = forms.DateField(
        widget=forms.TextInput(attrs={'class': 'datepicker'})
    )

    class Meta:
        model = Guest
        exclude = ['checked_out']


class GuestChangeForm(forms.ModelForm):
    departure_date = forms.DateField(
        widget=forms.TextInput(attrs={'class': 'datepicker'})
    )

    # def __init__(self, *args, **kwargs):
    #     super(GuestForm, self).__init__(*args, **kwargs)
    #     self.fields['departure_date'].empty_label = "Choose date"

    class Meta:
        model = Guest
        fields = ['surname', 'other_names', 'arrival_date', 'departure_date']
        # widgets = {
        #     'departure_date': forms.DateInput(attrs={'class': 'datepicker'}),
        # }


class CheckoutForm(forms.Form):
    pass


class BookingForm(forms.ModelForm):
    queryset = Facility.objects.all()
    facility = forms.ModelChoiceField(queryset, empty_label="Select Facility")
    booked_date = forms.DateField(
        widget=forms.TextInput(attrs={'class': 'datepicker'})
    )

    class Meta:
        model = Booking
        exclude = ['timestamp']

    def clean(self):
        _facility = self.cleaned_data['facility']
        _booked_date = self.cleaned_data['booked_date']
        reservations = Booking.objects.filter(
            booked_date=_booked_date, facility=_facility)
        if reservations:
            print ('reservations stage passed')
            for booked in reservations:
                if booked.facility.occupied:
                    print ('date is in use')
                    raise forms.ValidationError('Date already in use')


class RequisitionForm(forms.ModelForm):
    queryset = HouseKeeping.objects.all()
    item = forms.ModelChoiceField(queryset, empty_label="Select housekeeping item")

    class Meta:
        model = Requisition
        exclude = ['master']


class PurchaseForm(forms.ModelForm):

    class Meta:
        model = Purchase
        exclude = ['master']


class TransferForm(forms.ModelForm):

    class Meta:
        model = Transfer
        exclude = ['when']


class BillForm(forms.ModelForm):
    queryset = Guest.objects.filter(checked_out=False)
    guest = forms.ModelChoiceField(queryset, empty_label='select guest')
    bill_date = forms.DateField(
        widget=forms.TextInput(attrs={'class': 'datepicker'}))

    class Meta:
        model = Bill
        exclude = ['service']


class InventoryForm(forms.ModelForm):
    queryset = Item.objects.all()
    item = forms.ModelChoiceField(queryset, empty_label='Select Item')

    class Meta:
        model = Inventory
        exclude = ['location']


class InventoryOutflowForm(forms.ModelForm):
    queryset = Item.objects.all()
    item = forms.ModelChoiceField(queryset, empty_label='Select Item')

    class Meta:
        model = Inventory
        exclude = []

    def clean_location(self):
        if 'location' in self.cleaned_data:
            if self.cleaned_data['location'] == 4:
                raise forms.ValidationError('Select a valid location')
        return self.cleaned_data['location']

templates/room/bills.html
{% extends "room/base.html" %}
{% load static from staticfiles %}

{% block extra-css %}
<style>
    .panel {
        background-color: #f7ffe6;
    }
</style>
<link href="{% static 'tracker/css/dataTables.bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'tracker/css/dataTables.responsive.css' %}" rel="stylesheet">
{% endblock extra-css %}

{% block pageheader %}
    <h1 class="page-header">Bills for {{ service }}</h1>
{% endblock pageheader %}

{% block panelheader %}
Bills for {{ service }}
{% endblock panelheader %}

{% block breadcrumb %}
    <!-- START BREADCRUMB -->
    <ul class="breadcrumb">
        <li><a href="{% url 'hotel_guest_list' %}">Home</a></li>
        <li class="active">Bills for {{ service }}</li>
    </ul>
    <!-- END BREADCRUMB -->
{% endblock breadcrumb %}

{% block pagecontent %}
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Bills for {{ service }}</h3>
            </div>
            <div class="panel-body">
                <p>
                    <form method="get" action="">
                        <label>Search:
                            {{ form.term }}
                            {% comment %}<input type="text" name="term" class="form-control" placeholder='search' />{% endcomment %}
                        </label>
                    </form>
                </p>
                <div class="table-responsive">
    <table class="table table-striped table-bordered table-hover" id="dataTables-example">
         <thead>
             <tr>
                 <th>Guest </th>
                 <th>Description</th>
                 <th>Amount</th>
                 <th>Date</th>
                 <th>Pending</th>
             </tr>
         </thead>
         <tbody>
         {% for bill in bills %}
         <tr>
             <td>{{ bill.guest }}</td>
             <td>{{ bill.description }}</td>
             <td>{{ bill.amount }}</td>
             <td>{{ bill.bill_date }}</td>
             <td>{{ bill.pending|yesno }}</td>
         </tr>
         {% endfor %}
         </tbody>
     </table>
 </div>
            </div>
        </div>
    </div>

{% endblock pagecontent %}

{% block extra-footer-js %}
<script type="text/javascript" src="{% static 'tracker/js/jquery.dataTables.min.js' %}"></script>
<script type="text/javascript" src="{% static 'tracker/js/dataTables.bootstrap.min.js' %}"></script>
<script type="text/javascript">
$('#id_term').addClass('form-control');
$('#id_term').attr('placeholder', 'Search');
</script>
{% endblock extra-footer-js %}

templates/room/booked_facilities.html
{% extends "room/base.html" %}
{% load static from staticfiles %}

{% block extra-css %}
<style>
    .panel {
        background-color: #f7ffe6;
    }
</style>
<link href="{% static 'tracker/css/dataTables.bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'tracker/css/dataTables.responsive.css' %}" rel="stylesheet">
{% endblock extra-css %}

{% block pageheader %}
    <h1 class="page-header">Booked Facilities</h1>
{% endblock pageheader %}

{% block panelheader %}
List of Booked Facilities
{% endblock panelheader %}

{% block breadcrumb %}
    <!-- START BREADCRUMB -->
    <ul class="breadcrumb">
        <li><a href="{% url 'hotel_guest_list' %}">Home</a></li>
        <li class="active">List of Booked Facilities</li>
    </ul>
    <!-- END BREADCRUMB -->
{% endblock breadcrumb %}

{% block pagecontent %}
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Booked Facilities</h3>
                <a href="{% url 'booking_facility' %}" class="pull-right btn btn-primary"><i class="fa fa-home"></i> Book Facility</a>
            </div>
            <div class="panel-body">
                <p>
                    <form method="get" action="">
                        <label>Search:
                            {{ form.term }}
                            {% comment %}<input type="text" name="term" class="form-control" placeholder='search' />{% endcomment %}
                        </label>
                    </form>
                </p>
                <div class="table-responsive">
    <table class="table table-striped table-bordered table-hover" id="dataTables-example">
         <thead>
             <tr>
                 <th>Client </th>
                 <th>Facility </th>
                 <th>Cost</th>
                 <th>Booked Date </th>
                 <th>Details</th>
             </tr>
         </thead>
         <tbody>
         {% for booked in facilities %}
         <tr>
             <td>{{ booked.name }}</td>
             <td>{{ booked.facility.name }}</td>
             <td>{{ booked.facility.cost }}</td>
             <td>{{ booked.booked_date }}</td>
             <td><a href="{% url 'hotel_booking' id=booked.id %}" class="btn btn-success">Booking</a></td>
         </tr>
         {% endfor %}
         </tbody>
     </table>
 </div>
            </div>
        </div>
    </div>

{% endblock pagecontent %}

{% block extra-footer-js %}
<script type="text/javascript" src="{% static 'tracker/js/jquery.dataTables.min.js' %}"></script>
<script type="text/javascript" src="{% static 'tracker/js/dataTables.bootstrap.min.js' %}"></script>
<script type="text/javascript">
$('#id_term').addClass('form-control');
$('#id_term').attr('placeholder', 'Search');
</script>
{% endblock extra-footer-js %}

templates/room/booking.html
{% extends "room/base.html" %}
{% load static from staticfiles %}

{% block pageheader %}
<h1 class="page-header">Guest Checkout for Bayo Opadeyi</h1>
{% endblock pageheader %}

{% block panelheader %}
Booking Details
{% endblock panelheader %}

{% block breadcrumb %}
    <!-- START BREADCRUMB -->
    <ul class="breadcrumb">
      {% comment %}{% endcomment %}
        <li><a href="{% url 'home' %}">Home</a></li>
        <li class="active">Booking Details</li>
    </ul>
    <!-- END BREADCRUMB -->
{% endblock breadcrumb %}
facility
booked_date
amount
name
phone
timestamp
{% block pagecontent %}
<div class="row">
    <div class="col-lg-6">
      <div class="table-responsive">
          <table class="table table-striped table-bordered table-hover" id="dataTables-example">
               <tbody>
               <tr>
                   <td>Facility</td>
                   <td>{{ facility }}</td>
               </tr>
               <!--
               <tr>
                   <td>Room #</td>
                   <td>{{ guest.room }}</td>
               </tr>
               <tr>
                   <td>Accommodation Bill</td>
                   <td>{{ accomodation_bill }}</td>
               </tr>
               {% if bills %}
                {% for bill in bills %}
                 <tr>
                    <td>
                      {% if bill.service == 0 %}
                        Restaurant Bill
                      {% elif bill.service == 1 %}
                        Main Bar Bill
                      {% elif bill.service == 2 %}
                        Swimming Pool Bar Bill
                      {% elif bill.service == 3 %}
                        Laundry Bill
                      {% elif bill.service == 4 %}
                        Gym Bill
                      {% endif %}
                    </td>
                     <td>{{ bill.amount }}</td>
                 </tr>
               {% endfor %}
              {% endif %}
               <tr style="color:green">
                   <td>Deposited Amount</td>
                   <td>{{ guest.deposit }}</td>
               </tr>
              <tr style="color:red">
                   <td>Total</td>
                   <td>{{ total }}</td>
               </tr>
              -->
               <tr>

               </tr>
               </tbody>
           </table>
       </div>
       <!--
       <div>
            <a href="" type="submit" value="Check Out" class="btn btn-primary">Check Out</a>
       </div>
       -->
    </div>
    <div class="col-lg-6">
      <!--
       <div>
           <a href="" target="_blank" class="btn btn-primary">Print Bill</a>
       </div>
     -->
    </div>
</div>

{% endblock pagecontent %}

{% block extra-footer-js %}
<script type="text/javascript">
  $('#id_text').addClass('form-control');
  $('#id_num_workers').addClass('form-control');
</script>
{% endblock extra-footer-js %}

{% comment %}

{% load static from staticfiles %}
{% comment %}
<!-- {% load event_tags %} -->

{% block extra-css %}
<style>
  table {
    width: 100%;
  }
  .dayNumberNoEvents {
    padding: 10px 0;
    background: #eee;
    margin: 0;
    display: inline-block;
    width: 13.6%;
    text-align: center;
    margin-bottom: 5px;
    font-size: 12px;
    color: #777;
  }
  .dayNumber {
    padding: 10px 0;
    background: #fff;
    margin: 0;
    display: inline-block;
    width: 13.6%;
    text-align: center;
    margin-bottom: 5px;
    font-size: 12px;
    color: #777;
  }
</style>
{% endblock extra-css %} 

{% block pageheader %}
  <h1 class="page-header">Schedule for {{ facility.name }}</h1>
{% endblock pageheader %} 

{% block panelheader %} Guest Checkout {% endblock panelheader %} 

{% block breadcrumb %}
  <!-- START BREADCRUMB -->
  <ul class="breadcrumb">
    <li><a href="{% url 'hotel_guest_list' %}">Home</a></li>
    <li class="active">Schedule</li>
  </ul>
  <!-- END BREADCRUMB -->
{% endblock breadcrumb %} 


{% block pagecontent %}
  <div class="row">
    <div class="col-lg-12">
      <div id="calendar">
        
          {% event_calendar year month event_list %}
        
        {{event_list}}
        {{year}}
        {{month}}
        {{facility}}
    </div>
    </div>
  </div>
{% endblock pagecontent %} 


{% block extra-footer-js %}
  <script type="text/javascript">
    $("#id_text").addClass("form-control");
    $("#id_num_workers").addClass("form-control");
  </script>
{% endblock extra-footer-js %}
{% endcomment %}

templates/room/house_keeping.html
{% extends "room/base.html" %}
{% load static from staticfiles %}

{% block extra-css %}
<style>
    .panel {
        background-color: #f7ffe6;
    }
</style>
<link href="{% static 'tracker/css/dataTables.bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'tracker/css/dataTables.responsive.css' %}" rel="stylesheet">
{% endblock extra-css %}

{% block pageheader %}
    <h1 class="page-header">House Keeping</h1>
{% endblock pageheader %}

{% block panelheader %}
List of House Keeping Items
{% endblock panelheader %}

{% block breadcrumb %}
    <!-- START BREADCRUMB -->
    <ul class="breadcrumb">
        <li><a href="{% url 'hotel_guest_list' %}">Home</a></li>
        <li class="active">List of House Keeping Items</li>
    </ul>
    <!-- END BREADCRUMB -->
{% endblock breadcrumb %}

{% block pagecontent %}
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">House Keeping Items</h3>
                <a href="{% url 'hotel_requisition_new' %}" class="pull-right btn btn-primary"><i class="fa fa-plus"></i> New Requisition</a>
            </div>
            <div class="panel-body">
                <p>
                    <form method="get" action="">
                        <label>Search:
                            {{ form.term }}
                            {% comment %}<input type="text" name="term" class="form-control" placeholder='search' />{% endcomment %}
                        </label>
                    </form>
                </p>
                <div class="table-responsive">
    <table class="table table-striped table-bordered table-hover" id="dataTables-example">
         <thead>
             <tr>
                 <th>Name </th>
                 <th>Available Quantity</th>
                 <th>Reorder Level</th>
                 <th>Rate</th>
             </tr>
         </thead>
         <tbody>
         {% for item in items %}
         <tr>
             <td>{{ item.name }}</td>
             <td>{{ item.quantity }}</td>
             <td>{{ item.reorder_level }}</td>
             <td>{{ item.rate }}</td>
         </tr>
         {% endfor %}
         </tbody>
     </table>
 </div>
            </div>
        </div>
    </div>

{% endblock pagecontent %}

{% block extra-footer-js %}
<script type="text/javascript" src="{% static 'tracker/js/jquery.dataTables.min.js' %}"></script>
<script type="text/javascript" src="{% static 'tracker/js/dataTables.bootstrap.min.js' %}"></script>
<script type="text/javascript">
$('#id_term').addClass('form-control');
$('#id_term').attr('placeholder', 'Search');
</script>
{% endblock extra-footer-js %}

templates/room/new_booking.html
{% extends "room/base.html" %}

{% load static from staticfiles %}

{% block pageheader %}
    <h1 class="page-header">New Booking</h1>
{% endblock pageheader %}

{% block panelheader %}
New Booking
{% endblock panelheader %}

{% block breadcrumb %}
    <!-- START BREADCRUMB -->
    <ul class="breadcrumb">
        <li><a href="{% url 'hotel_guest_list' %}">Home</a></li>
        <li class="active">New Booking</li>
    </ul>
    <!-- END BREADCRUMB -->
{% endblock breadcrumb %}

{% block pagecontent %}
<div class="row">
    <div class="col-md-12">
        <form id="action_form" action="" method="post" role="form" class="form-horizontal">{% csrf_token %}
        <div class="panel panel-default">
            
            {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                        {{ error }}
                    </div>
                {% endfor %}
            {% endif %}
            <div class="panel-heading"><h3>New Booking</h3></div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-6">

                        {% for fld in form %}
                        <div class="form-group">
                            {% if fld.errors %}
                                <div class="alert alert-danger">
                                    {{fld.errors}}
                                </div>
                            {% endif %}
                            <label for={{fld.id_for_label}} class="col-md-3 control-label">{{fld.label}}</label>
                            <div class="col-md-9">
                                {{ fld}}
                            </div>
                        </div>
                        {% endfor %}
                      
                    </div>
                </div>
            </div>
     
            <div class="panel-footer">
                <div class="col-md-6 col-md-offset-3">
                <button type="submit" value="Save Booking Information" class="btn btn-primary btn-block">Save Booking Information</button>
                    
                </div>
                <div class="col-md-3"></div>
            </div>
    
        </div>
    </form>        
    </div>
</div>
{% endblock pagecontent %}

{% block extra-footer-js %}
<script type="text/javascript" src="{% static 'js/bootstrap-datepicker.min.js' %}"></script>

<script type="text/javascript">
    $('input').addClass('form-control');
    $('select').addClass('form-control');

    $('#id_address').addClass('form-control');
    $('#id_subject').addClass('form-control');
    $('#id_priority').addClass('form-control');
    $('#id_minuted_to').addClass('form-control');
    $('#id_document').addClass('form-control');
    $('#id_document_name').addClass('form-control');
   
    $('#id_due_date').addClass('form-control');
    $('#id_due_date').datepicker({
        autoclose: true
    });
    $('#id_description').addClass('form-control');

    var jvalidate = $("#action_form").validate({
        rules: {
            mda: {
                required: true,
                minlength: 2,
            },
            document_name: {
                required: true
            },
            document: {
                required: true
            },
            subject: {
                required: true
            },
            minuted_to: {
                required: true
            },
            priority: {
                required: true
            },
            due_date: {
                required: true,
                date: true
            }
        }
    })
</script>
 <script type="text/javascript">
            var jvalidate = $("#jvalidate").validate({
                ignore: [],
                rules: {                                            
                        login: {
                                required: true,
                                minlength: 2,
                                maxlength: 8
                        },
                        password: {
                                required: true,
                                minlength: 5,
                                maxlength: 10
                        },
                        're-password': {
                                required: true,
                                minlength: 5,
                                maxlength: 10,
                                equalTo: "#password2"
                        },
                        age: {
                                required: true,
                                min: 18,
                                max: 100
                        },
                        email: {
                                required: true,
                                email: true
                        },
                        date: {
                                required: true,
                                date: true
                        },
                        credit: {
                                required: true,
                                creditcard: true
                        },
                        site: {
                                required: true,
                                url: true
                        }
                    }                                        
                });                                    

        </script>
{% endblock extra-footer-js %}