djordan/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from django.conf import settings
from djordan import views


urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('room/', include('room.urls')),
    path('profile/', include('user_profile.urls')),
    # path('accounts/login/', TemplateView.as_view(template_name="registration/login.html"), name='login'),
    # path('accounts/logout/', auth_views.logout_then_login, name='logout'),
    # path('accounts/login/', auth_views.LoginView.as_view(template_name='user_profile/login.html')),
    path('accounts/', include('django.contrib.auth.urls')), # django built-in auth library REGISTRATION FOLDER
    # path('events2/', include('events2.urls')),
]

room/urls.py
from django.urls import path

from room import views
from room.views import GeneratePDF


urlpatterns = [
    path('guests/', views.guest_list, name='hotel_guest_list'),
    path('occupied/', views.occupied_guest_list, name='occupied_guest_list'),
    path('checkedout/', views.checkedout_guest_list, name='checkedout_guest_list'),
    path('newguests/', views.new_guest, name='hotel_new_guest'),
    path('rooms/', views.room_list, name='hotel_room_list'),
    path('checkout/<int:id>/', views.pre_check_out, name='pre_check_out'),
    path('checkout/<int:id>/pay/', views.pay_check_out, name='pay_check_out'),
    path('checkout/<int:id>/paid/', views.paid_check_out, name='paid_check_out'),
    path('change/<int:id>/', views.change_departure_date, name='change_date'),
    path('facilities/', views.facility_list, name='hotel_facility_list'),
    path('booking/<int:id>/', views.booking, name='hotel_booking'),
    path('facility/booking/', views.booking_facility, name='booking_facility'),
    path('booked/facility', views.booked_facilities, name='booked_facilities'),
    # <int:day>/<int:month>/<int:year>/
    path('housekeeping/',
         views.housekeeping, name='hotel_housekeeping_list'),
    path('requisition/<int:id>/',
         views.requisition, name='hotel_requisition'),
    path('requisition/', views.new_requisition, name='hotel_requisition_new'),
    path('bill/<int:id>/', views.bills, name='hotel_bill_list'),
    path('inventory/<int:id>/', views.inventory, name='hotel_inventory_list'),
    path('purchase/<int:id>/', views.purchase, name='hotel_purchase'),
    path('purchase/', views.new_purchase, name='hotel_purchase_new'),
    path('transfer/', views.transfer, name='hotel_transfer'),
    path('print/<int:id>/', GeneratePDF.as_view(), name='print_bill_pdf'),
    path('occupied/dates/', views.view_room_with_date, name='view_room_with_date'),
]

room/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone


class RoomType(models.Model):
    name = models.CharField(max_length=100)
    cost = models.DecimalField(decimal_places=2, max_digits=10)
    deposit = models.DecimalField(decimal_places=2, max_digits=10)

    def __str__(self):
        return self.name


class Room(models.Model):
    room_number = models.CharField(max_length=100)
    room_type = models.ForeignKey(RoomType, on_delete=models.CASCADE)
    occupied = models.BooleanField(default=False)

    def __str__(self):
        return '{} - {} ({})'.format(
            self.room_number, self.room_type, self.room_type.cost)


class CompanyAccount(models.Model):
    name = models.CharField(max_length=100)
    address = models.TextField()
    balance = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.name


class Guest(models.Model):
    SELECT = 0
    FEMALE = 1
    MALE = 2
    SEXES = enumerate(('Select', 'Female', 'Male'))

    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    deposit = models.DecimalField(decimal_places=2, max_digits=10)
    surname = models.CharField(max_length=200)
    other_names = models.CharField(max_length=200)
    sex = models.PositiveIntegerField(choices=SEXES, default=0)
    nationality = models.CharField(max_length=100)
    occupation = models.CharField(max_length=100)
    address = models.TextField(blank=True)
    car_number = models.CharField(max_length=20)
    phone_number = models.CharField(max_length=20)
    email = models.EmailField()
    purpose = models.CharField(max_length=20, blank=True)
    arriving_from = models.CharField(max_length=20, blank=True)
    travelling_to = models.CharField(max_length=20, blank=True)
    passport_no = models.CharField(max_length=20, blank=True)
    arrival_date = models.DateField(default=timezone.now)
    departure_date = models.DateField(null=True, blank=True)
    account = models.ForeignKey(CompanyAccount, null=True, blank=True, on_delete=models.SET_NULL)
    num_adults = models.IntegerField()
    num_children = models.IntegerField()
    checked_out = models.BooleanField(default=False)

    def __str__(self):
        return self.surname

    @property
    def full_name(self):
        return '{} {}'.format(self.other_names, self.surname)

    class Meta:
        ordering = ["-id", "-arrival_date"]


class Facility(models.Model):
    name = models.CharField(max_length=200)
    cost = models.DecimalField(max_digits=10, decimal_places=2)
    occupied = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Booking(models.Model):
    facility = models.ForeignKey(Facility, on_delete=models.CASCADE)
    booked_date = models.DateField()
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    name = models.CharField(max_length=200, blank=True)
    phone = models.CharField(max_length=50, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return unicode(self.facility)


class HouseKeeping(models.Model):
    name = models.CharField(max_length=100)
    rate = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.IntegerField()
    reorder_level = models.IntegerField(default=1)

    def __str__(self):
        return self.name


class RequisitionMaster(models.Model):
    date = models.DateField(default=timezone.now)

    def __str__(self):
        return self.date.strftime('%Y-%m-%d')


class Requisition(models.Model):
    item = models.ForeignKey(HouseKeeping, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    rate = models.DecimalField(max_digits=10, decimal_places=2)
    master = models.ForeignKey(RequisitionMaster, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return unicode(self.item)


class Bill(models.Model):
    RESTAURANT = 0
    MAIN_BAR = 1
    SWIMMING_POOL_BAR = 2
    LAUNDRY = 3
    GYM = 4
    SERVICES = enumerate(
        ('Restaurant', 'Main Bar', 'Pool Bar', 'Laundry', 'Gym'))

    guest = models.ForeignKey(Guest, null=True, on_delete=models.SET_NULL)
    amount = models.DecimalField(decimal_places=2, max_digits=10)
    bill_date = models.DateField(default=timezone.now)
    paid = models.BooleanField(default=False)
    description = models.TextField(blank=True)
    service = models.PositiveIntegerField(choices=SERVICES)

    def __str__(self):
        return '{}'.format(self.amount)

    @property
    def pending(self):
        return not self.paid


class Item(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.name


class Inventory(models.Model):
    RESTAURANT = 0
    MAIN_BAR = 1
    SWIMMING_POOL_BAR = 2
    STORE = 3
    SELECT = 4
    LOCATIONS = enumerate(
        ('Restaurant', 'Main Bar', 'Pool Bar', 'Store', 'Select Location'))

    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    location = models.PositiveIntegerField(choices=LOCATIONS, default=4)

    def __str__(self):
        return unicode(self.item)


class PurchaseMaster(models.Model):
    when = models.DateField(default=timezone.now)

    def __str__(self):
        return self.when.strftime('%d-%m-%Y')


class Purchase(models.Model):
    master = models.ForeignKey(PurchaseMaster, null=True, on_delete=models.SET_NULL)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return unicode(self.inventory)

    @property
    def total(self):
        return self.quantity * self.price


class Transfer(models.Model):
    RESTAURANT = 0
    MAIN_BAR = 1
    SWIMMING_POOL_BAR = 2
    LOCATIONS = enumerate(
        ('Restaurant', 'Main Bar', 'Pool Bar'))

    destination = models.PositiveIntegerField(choices=LOCATIONS)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    when = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return '{} - {}'.format(self.destination, self.item)

room/forms.py
from django import forms

from room.models import Guest, Room, Booking, Requisition, Purchase,\
    Transfer, Facility, HouseKeeping, Bill, Inventory, Item


class GuestForm(forms.ModelForm):
    queryset = Room.objects.filter(occupied=False)
    room = forms.ModelChoiceField(queryset, empty_label="Select type")
    departure_date = forms.DateField(
        widget=forms.TextInput(attrs={'class': 'datepicker'})
    )

    class Meta:
        model = Guest
        exclude = ['checked_out']


class GuestChangeForm(forms.ModelForm):
    departure_date = forms.DateField(
        widget=forms.TextInput(attrs={'class': 'datepicker'})
    )

    # def __init__(self, *args, **kwargs):
    #     super(GuestForm, self).__init__(*args, **kwargs)
    #     self.fields['departure_date'].empty_label = "Choose date"

    class Meta:
        model = Guest
        fields = ['surname', 'other_names', 'arrival_date', 'departure_date']
        # widgets = {
        #     'departure_date': forms.DateInput(attrs={'class': 'datepicker'}),
        # }


class CheckoutForm(forms.Form):
    pass


class BookingForm(forms.ModelForm):
    queryset = Facility.objects.all()
    facility = forms.ModelChoiceField(queryset, empty_label="Select Facility")
    booked_date = forms.DateField(
        widget=forms.TextInput(attrs={'class': 'datepicker'})
    )

    class Meta:
        model = Booking
        exclude = ['timestamp']

    def clean(self):
        _facility = self.cleaned_data['facility']
        _booked_date = self.cleaned_data['booked_date']
        reservations = Booking.objects.filter(
            booked_date=_booked_date, facility=_facility)
        if reservations:
            print ('reservations stage passed')
            for booked in reservations:
                if booked.facility.occupied:
                    print ('date is in use')
                    raise forms.ValidationError('Date already in use')


class RequisitionForm(forms.ModelForm):
    queryset = HouseKeeping.objects.all()
    item = forms.ModelChoiceField(queryset, empty_label="Select housekeeping item")

    class Meta:
        model = Requisition
        exclude = ['master']


class PurchaseForm(forms.ModelForm):

    class Meta:
        model = Purchase
        exclude = ['master']


class TransferForm(forms.ModelForm):

    class Meta:
        model = Transfer
        exclude = ['when']


class BillForm(forms.ModelForm):
    queryset = Guest.objects.filter(checked_out=False)
    guest = forms.ModelChoiceField(queryset, empty_label='select guest')
    bill_date = forms.DateField(
        widget=forms.TextInput(attrs={'class': 'datepicker'}))

    class Meta:
        model = Bill
        exclude = ['service']


class InventoryForm(forms.ModelForm):
    queryset = Item.objects.all()
    item = forms.ModelChoiceField(queryset, empty_label='Select Item')

    class Meta:
        model = Inventory
        exclude = ['location']


class InventoryOutflowForm(forms.ModelForm):
    queryset = Item.objects.all()
    item = forms.ModelChoiceField(queryset, empty_label='Select Item')

    class Meta:
        model = Inventory
        exclude = []

    def clean_location(self):
        if 'location' in self.cleaned_data:
            if self.cleaned_data['location'] == 4:
                raise forms.ValidationError('Select a valid location')
        return self.cleaned_data['location']

templates/store/stock_levels.html
{% extends "room/base.html" %}
{% load static from staticfiles %}

{% block extra-css %}
<style>
    .panel {
        background-color: #f7ffe6;
    }
</style>
<link href="{% static 'tracker/css/dataTables.bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'tracker/css/dataTables.responsive.css' %}" rel="stylesheet">
{% endblock extra-css %}

{% block pageheader %}
    <h1 class="page-header">Stock Inflow/Outflow </h1>
{% endblock pageheader %}

{% block panelheader %}
Stock Inflow/Outflow 
{% endblock panelheader %}

{% block breadcrumb %}
    <!-- START BREADCRUMB -->
    <ul class="breadcrumb">
        <li><a href="{% url 'hotel_guest_list' %}">Home</a></li>
        <li class="active">Stock Inflow/Outflow Level</li>
    </ul>
    <!-- END BREADCRUMB -->
{% endblock breadcrumb %}

{% block pagecontent %}
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Stock Inflow/Outflow Level</h3>
            </div>
            <div class="panel-body">
                <p>
                    {% comment %}
                    <form method="get" action="">
                        <label>Search:
                            {{ form.term }}
                            <input type="text" name="term" class="form-control" placeholder='search' />
                        </label>
                    </form>
                    {% endcomment %}
                </p>
                <div class="table-responsive">
    <table class="table table-striped table-bordered table-hover" id="dataTables-example">
         <thead>
             <tr>
                 <th>Room N0.</th>
                 <th>Room Type</th>
                 <th>Room Cost</th>
                 <th>Occupied?</th>
                 <!-- <th>Details</th> -->
             </tr>
         </thead>
         <tbody>
         {% for item in stock %}
         <tr>
             <td>{{ item }}</td>
             <td>{{ room.room_type }}</td>
             <td>{{ room.room_type.cost }}</td>
             <td>
                 {% if room.occupied %}
                    <span class="btn-success" style="padding: 5px;">YES</span>
                 {% else %}
                    <span class="btn-danger" style="padding: 5px;">NO</span>
                 {% endif %}
             </td>
             <!-- <td><a href="" class="btn btn-success">details</a></td> -->
         </tr>
         {% endfor %}
         </tbody>
     </table>
 </div>
            </div>
        </div>
    </div>

{% endblock pagecontent %}

{% block extra-footer-js %}
<script type="text/javascript" src="{% static 'tracker/js/jquery.dataTables.min.js' %}"></script>
<script type="text/javascript" src="{% static 'tracker/js/dataTables.bootstrap.min.js' %}"></script>
<script type="text/javascript">
$('#id_term').addClass('form-control');
$('#id_term').attr('placeholder', 'Search');
</script>
{% endblock extra-footer-js %}

templates/store/stock_outflow.html
{% extends "room/base.html" %}

{% load static from staticfiles %}


{% block pageheader %}
    <h1 class="page-header">Enter Stock Outflow</h1>
{% endblock pageheader %}

{% block panelheader %}
Enter Stock Outflow
{% endblock panelheader %}

{% block breadcrumb %}
    <!-- START BREADCRUMB -->
    <ul class="breadcrumb">
        <li><a href="{% url 'hotel_guest_list' %}">Home</a></li>
        <li class="active">Enter Stock Outflow </li>
    </ul>
    <!-- END BREADCRUMB -->
{% endblock breadcrumb %}

{% block pagecontent %}

<div class="row">
    <div class="col-md-12">
        <form id="action_form" action="" method="post" role="form" class="form-horizontal">{% csrf_token %}
        <div class="panel panel-default">
            
            {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                        {{ error }}
                    </div>
                {% endfor %}
            {% endif %}
            <div class="panel-heading"><h3>Enter Stock Outflow </h3></div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-6">

                        
                        <div class="form-group">
                            {% if form.item.errors %}
                                <div class="alert alert-danger">
                                    {{form.item.errors}}
                                </div>
                            {% endif %}
                            <label class="col-md-3 control-label">{{form.item.label}}</label>
                            <div class="col-md-9">
                                {{ form.item }}
                            </div>
                        </div>                       

                        <div class="form-group">
                            {% if form.location.errors %}
                                <div class="alert alert-danger">
                                    {{form.location.errors}}
                                </div>
                            {% endif %}
                            <label class="col-md-3 control-label">{{form.location.label}}</label>
                            <div class="col-md-9">
                                {{ form.location }}
                            </div>
                        </div>
                        
                         <div class="form-group">
                            {% if form.quantity.errors %}
                                <div class="alert alert-danger">
                                    {{form.quantity.errors}}
                                </div>
                            {% endif %}
                            <label class="col-md-3 control-label">{{form.quantity.label}}</label>
                            <div class="col-md-9">
                                {{ form.quantity }}
                            </div>
                        </div>

                        {% comment %}
                        {% for fld in form %}
                        <div class="form-group">
                            {% if fld.errors %}
                                <div class="alert alert-danger">
                                    {{fld.errors}}
                                </div>
                            {% endif %}
                            <label for={{fld.id_for_label}} class="col-md-3 control-label">{{fld.label}}</label>
                            <div class="col-md-9">
                                {{ fld}}
                            </div>
                        </div>
                        {% endfor %}
                        {% endcomment %}
                      
                    </div>
                </div>
            </div>
     
            <div class="panel-footer">
                <div class="col-md-4 col-md-offset-2">
                <button type="submit" value="Save Guest Information" class="btn btn-primary btn-block">Save New Inventory</button>
                    
                </div>
                <div class="col-md-3"></div>
            </div>
    
        </div>
    </form>        
    </div>
</div>
{% endblock pagecontent %}



{% block extra-footer-js %}
<script type="text/javascript" src="{% static 'js/bootstrap-datepicker.min.js' %}"></script>


<script type="text/javascript">
    $('#id_quantity').addClass('form-control');
    $('#id_item').addClass('form-control');
    $('#id_location').addClass('form-control');

    {% comment %}
    $('input').addClass('form-control');
    $('select').addClass('form-control');
    $('textarea').addClass('form-control');
    {% endcomment %}
</script>
{% endblock extra-footer-js %}

<!-- <form id="form" role="form" action="url 'search-submit'" method="post">
    {% csrf_token %}
    <input name="search" id="search" type="search" placeholder="Search"/>
    <button type="submit">Submit</button>
</form> -->

templates/store/store.html
{% extends "room/base.html" %}

{% load static from staticfiles %}


{% block pageheader %}
    <h1 class="page-header">Stock Inflow</h1>
{% endblock pageheader %}

{% block panelheader %}
Stock Inflow
{% endblock panelheader %}

{% block breadcrumb %}
    <!-- START BREADCRUMB -->
    <ul class="breadcrumb">
        <li><a href="{% url 'hotel_guest_list' %}">Home</a></li>
        <li class="active">Stock Inflow</li>
    </ul>
    <!-- END BREADCRUMB -->
{% endblock breadcrumb %}

{% block pagecontent %}

<div class="row">
    <div class="col-md-12">
        <form id="action_form" action="" method="post" role="form" class="form-horizontal">{% csrf_token %}
        <div class="panel panel-default">
            
            {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                        {{ error }}
                    </div>
                {% endfor %}
            {% endif %}
            <div class="panel-heading"><h3>Enter Stock Inflow</h3></div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-6">

                        
                        <div class="form-group">
                            {% if form.item.errors %}
                                <div class="alert alert-danger">
                                    {{form.item.errors}}
                                </div>
                            {% endif %}
                            <label class="col-md-3 control-label">{{form.item.label}}</label>
                            <div class="col-md-9">
                                {{ form.item }}
                            </div>
                        </div>
                        <div class="form-group">
                            {% if form.quantity.errors %}
                                <div class="alert alert-danger">
                                    {{form.quantity.errors}}
                                </div>
                            {% endif %}
                            <label class="col-md-3 control-label">{{form.quantity.label}}</label>
                            <div class="col-md-9">
                                {{ form.quantity }}
                            </div>
                        </div>

                        <div class="form-group">
                            {% if form.location.errors %}
                                <div class="alert alert-danger">
                                    {{form.location.errors}}
                                </div>
                            {% endif %}
                            <label class="col-md-3 control-label">{{form.location.label}}</label>
                            <div class="col-md-9">
                                {{ form.location }}
                            </div>
                        </div>
                        

                        {% comment %}
                        {% for fld in form %}
                        <div class="form-group">
                            {% if fld.errors %}
                                <div class="alert alert-danger">
                                    {{fld.errors}}
                                </div>
                            {% endif %}
                            <label for={{fld.id_for_label}} class="col-md-3 control-label">{{fld.label}}</label>
                            <div class="col-md-9">
                                {{ fld}}
                            </div>
                        </div>
                        {% endfor %}
                        {% endcomment %}
                      
                    </div>
                </div>
            </div>
     
            <div class="panel-footer">
                <div class="col-md-4 col-md-offset-2">
                <button type="submit" value="Save Guest Information" class="btn btn-primary btn-block">Save New Inventory</button>
                    
                </div>
                <div class="col-md-3"></div>
            </div>
    
        </div>
    </form>        
    </div>
</div>
{% endblock pagecontent %}



{% block extra-footer-js %}
<script type="text/javascript" src="{% static 'js/bootstrap-datepicker.min.js' %}"></script>


<script type="text/javascript">
    $('#id_quantity').addClass('form-control');
    $('#id_item').addClass('form-control');
    $('#id_bill_date').addClass('form-control');
    $('#id_paid').addClass('form-check');
    $('#id_description').addClass('form-control');
    

    {% comment %}
    $('input').addClass('form-control');
    $('select').addClass('form-control');
    $('textarea').addClass('form-control');
    {% endcomment %}
</script>
{% endblock extra-footer-js %}

<!-- <form id="form" role="form" action="url 'search-submit'" method="post">
    {% csrf_token %}
    <input name="search" id="search" type="search" placeholder="Search"/>
    <button type="submit">Submit</button>
</form> -->